import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import { convertGoogleDocumentToJson, convertJsonToMarkdown } from '../src/utils/googleDocsParser'
import { useEffect } from 'react'


export default function Home() {
  useEffect(() => {
    const teste = async () => {
      // const data = await fetch('/api/hello')
      // const res = await data.json()

      // console.log(res)
      const data = await fetch(`https://docs.googleapis.com/v1/documents/1kteetCYUboGol2GNiJpsMfsv7JhebpiRZKWu28WKTyw?key=AIzaSyABR4vevKdDep_bAxRihEpfXW6SAeOY_mM`)
      const res = await data.json()
      console.log(res)
    }

    teste()
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
         This is a test of an automated email generator using RSS feed
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
